//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgeSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Toptancilar
    {
        public int FirmaID { get; set; }
        public string FirmaAdi { get; set; }
        public string YetkiliAdSoyad { get; set; }
        public Nullable<double> Alinacak { get; set; }
        public Nullable<double> Verilecek { get; set; }
        public string Telefon { get; set; }
        public string Email { get; set; }
        public string Adres { get; set; }
        public string VergiNumarasi { get; set; }
        public string OzetNotlar { get; set; }
    }
}
