//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BilgeSoft
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zno
    {
        public int Id { get; set; }
        public Nullable<int> ZNumara { get; set; }
    }
}
